Connection to MONGODB with mongoose and email validation
Samueljit/movie-rank pull request #3
Opened 2022-02-05 03:32 UTC by Samueljit

2022-02-10 01:28 UTC, Tavo5691 requested changes

2022-02-10 01:28 UTC, Tavo5691 commented on models/user.js
> +        default: true
Esto es para poder filtrar los usuarios que están activos, no?

Pongamosle `active` mejor y que sea required.

2022-02-10 01:28 UTC, Tavo5691 commented on helpers/validationDB.js
> +    // Verificar si el correo existe
Renombremoslo a `hasRepeatedEmail`, ya con ese nombre podemos borrar este comentario.

2022-02-10 01:28 UTC, Tavo5691 commented on helpers/validationDB.js
> +    if ( existEmail ) {
Cambiemoslo a `foundEmail` como con el Role.

2022-02-10 01:28 UTC, Tavo5691 commented on helpers/validationDB.js
> +        throw new Error(`The email: ${ email } is already exist in the DB`);
Cambiar por `The email: ${ email } already exists in the DB`

2022-02-10 01:28 UTC, Tavo5691 commented on models/role.js
> +const { Schema, model } = pkg;
No puedo levantar la app porque no tengo Mongo local todavia, queria probar algo. 

Prueba cambiando esto por:

import mongoose from 'mongoose';
const { Schema, model } = mongoose;

A ver si funciona igual. Si no, no hay problema.

2022-02-10 01:28 UTC, Tavo5691 commented on controllers/users.js
>      })
👍 👍

2022-02-13 21:35 UTC, Samueljit commented
this is the merge with the requested changes in the pr.

2022-02-16 01:31 UTC, Tavo5691 requested changes
Pila cuando vayas a commitear código que no se cambien todas las clases de la nada

2022-02-16 01:31 UTC, Tavo5691 commented on models/user.js
> +        type: required
Te vorviste loco jajaja

Pon:

type: Boolean,
required: true,
default: true

2022-02-16 01:31 UTC, Tavo5691 commented on helpers/validationDB.js
> +    // Verificar si el correo existe
Borra el comentario

2022-02-16 01:31 UTC, Tavo5691 commented on routes/users.js
> +import {emailRegistered, isValidRole} from '../helpers/validationDB.js'
`emailRegistered` ya no existe, ahora es `hasRepeatedEmail`

2022-02-16 01:31 UTC, Tavo5691 commented on helpers/validationDB.js
> +        throw new Error(`Cambiar por The email: ${ email } already exists in the DB`);
Adiós luz que te apagaste jajajaja el espanglish

2022-02-16 03:03 UTC, Tavo5691 approved these changes

2022-02-16 03:04 UTC, merged